version: '3.7'
services:
  erp_db:
    container_name: epr_db
    image: mysql:5.7
  enviroment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: erp
  restart: always
  volumes:
    - mysql-data:/var/lib/mysql

volumes:
  mysql-data